import 'bootstrap/dist/css/bootstrap.min.css'
import { Inter as FontSans } from "next/font/google"
import { cn } from '@/lib/utils'
import ThemeProvider from '@/lib/theme-provider'
import "@/styles/globals.css";
import { Toaster } from '@/components/ui/toaster'
import { Metadata } from 'next';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen min-w-screen bg-background font-sans antialiased"
      )}>

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className='min-h-screen min-w-full'>
            {children}
          </main>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  )
}
