import 'bootstrap/dist/css/bootstrap.min.css'
import { MainNav } from '@/components/MainNav'
import { Inter as FontSans } from "next/font/google"
import { cn } from '@/lib/utils'
import ThemeProvider from '@/lib/theme-provider'
import "@/styles/globals.css";
import { SideBar } from '@/components/Sidebar'
import { sideBar } from '@/configs/sideBar'
import { Toaster } from '@/components/ui/toaster'
import { Metadata } from 'next'
export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen min-w-screen bg-background font-sans antialiased",
        fontSans.variable
      )}>

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MainNav />

          <main className='flex'>
            <SideBar items={sideBar.sidebarNav} />
            {children}
          </main>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  )
}
